# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2ef326c5850c36fb57d14056e9ba91a8aaf1d00631fc839c8b95aeebe5d2f72a17afeebb6da515bfda6a467d020ea721f7b984aa0e5d218f3a45651dff0edbe

test:
  secret_key_base: 2729acdfadfc92737ff92581c0c4fa7f9a1879945f1c5a433ff5fe262539c493f91fa47083d752948b9727005edac7002ebc731a4d12a9898e44bf4808e74d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
